<?php

/**
 * @file
 * @todo.
 */

/**
 * Implements hook_help().
 */
function views_column_class_help($section = 'admin/help#views_column_class', $arg = NULL) {
  $output = '';
  switch ($section) {
    case 'admin/help#views_column_class':
      $output = t('<p>This module allows you to assign class to the listed items of an ordered or unordered list that is generate as a display in views.</p>
      <p>The main application for this is when generating blocks that will be styled to appear in columns.</p>	
      <p>It is even more powerful when used with themes with responsive design because it encourages you to use grid class to specify the width of your block which can then be given a different width depending on the gird that is being apply based upon the screen resolution.</p>
      <p>You can address the problem of having margin on items that in your left and right columns by giving those on the left a class of alpha and those on the right a class of omega.</p>
      <p>These means that you can avoid setting fixed widths on blocks that wrap your view and giving the outer wrapping div and overflow of hidden to accommodate the margin on the right of your blocks.</p>
      <p>Additionally, you can apply multiple column class settings using the advanced classes textarea. This has the potential of allow you to display your items in 4 columns for higher screen resolutions and 2 columns for your modile devices.</p>');
      break;
  }
  return $output;
}

/**
 * Implements hook_views_api().
 */
function views_column_class_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements template_preprocess_HOOK().
 *
 * Populate each instance of $variables['classes'][$id] where $id is the current 
 * position in the view results with the classes specified by the primary and 
 * advanced settings in our form.
 *
 * @see template_preprocess_views_view_list()
 * @see views_column_class_prepare_advanced()
 * @see views_column_class_set_row_classes()
 */
function template_preprocess_views_view_column_class(&$variables) {
  template_preprocess_views_view_list($variables);

  $rows = $variables['rows'];
  $view = $variables['view'];
  $options = $view->style_plugin->options;
  $columns = $options['columns'];
  $advanced_classes = views_column_class_prepare_advanced($options['advanced_classes']);

  $count = 0;

  foreach ($rows as $id => $row) {

    views_column_class_set_row_classes($variables['classes'][$id], $count, $columns, $options['class_column_left'], $options['class_column_right'], $options['column_class_prefix']);

    foreach ($advanced_classes as $adv_class) {
      views_column_class_set_row_classes($variables['classes'][$id], $count, $adv_class[0], $adv_class[1], $adv_class[2], $adv_class[3]);
    }

    // Flatten the classes to a string for each row for the template file.
    $variables['classes_array'][$id] = implode(' ', $variables['classes'][$id]);

    $count++;
  }
}

/**
 * Prepare array of values that will be applied as classes to a row
 * 
 * @param mixed $vars_class_id
 *   Referenced value to store the classes to be be applied to the row template.
 * 
 * @param int $count
 *   The current row in the view results.
 * 
 * @param int $columns
 *   Number of columns imposed by the defined settings.
 * 
 * @param string $class_left
 *   Add this value in the array to be applied if current position is in the 
 *   first column of results.
 * 
 * @param string $class_right
 *   Add this value in the array to be applied if current position is in the 
 *   last column of results.
 * 
 * @param string $column_class_prefix
 *   Add this value in each array if not blank to be applied. The current column 
 *   position will be appended to this string.
 */
function views_column_class_set_row_classes(&$variables_class_id, $count, $columns, $class_left, $class_right, $column_class_prefix) {    
  if ($columns > 0) {
    if ($count % $columns == 0 && $class_left) {
      $variables_class_id[] = $class_left;
    }
    if (($count + 1) % $columns == 0 && $class_right) {
      $variables_class_id[] = $class_right;
    }
    if (trim($column_class_prefix) != '') {
      $variables_class_id[] = trim($column_class_prefix) . (($count % $columns) + 1);
    }
  }
}

/**
 * Parse the input from the Advanced classes textarea.
 * 
 * @param string $advanced
 *   Expects one entry per line with each line accepting up to 4 values using | as a delimiter.
 *   (e.g. columns|class_left|class_right|column_class_prefix)
 *
 * @return
 *   array that has a depth of 2
 *   a collection of arrays of 4 values
 *   1. The columns
 *   2. The class to apply to the blocks in the left column
 *   3. The class to apply to the blocks in the right column
 *   4. The class to apply as a prefix in each column that will be followed by the column number
 */
function views_column_class_prepare_advanced($advanced) {
  $advanced_parsed = array();

  $advanced = trim($advanced);

  if ($advanced != '') {

    $advanced_array = explode("\n", $advanced);

    if (count($advanced_array) > 0) {
      foreach ($advanced_array as $id => $adv_row) {
        $adv_row_arr = explode('|', $adv_row);
        $row_elements = count($adv_row_arr);
        $row_values = array();

        if ($row_elements >= 1 && (int) $adv_row_arr[0] > 0) {
          $advanced_parsed[] = array(
            $adv_row_arr[0],
            ($row_elements >= 2 && trim($adv_row_arr[1])!='') ? trim($adv_row_arr[1]) : FALSE,
            ($row_elements >= 3 && trim($adv_row_arr[2])!='') ? trim($adv_row_arr[2]) : FALSE,
            ($row_elements >= 4 && trim($adv_row_arr[3])!='') ? trim($adv_row_arr[3]) : '',
          );
        }
      }
    }

  }

  return $advanced_parsed;
}
